{
    "name": "Saudi School Finance",
    "summary": "School students, guardians, fees, installments, approvals and accounting overview",
    "version": "19.0.1.0.5",
    "category": "Accounting",
    "author": "TelNova",
    "license": "LGPL-3",
    "depends": [
        "account",
        "l10n_sa",
        "mail",
        "om_account_accountant",
        "om_account_asset",
        "om_account_budget",
        "om_account_followup",
    ],
    "data": [
        "security/school_finance_security.xml",
        "security/ir.model.access.csv",
        "security/school_finance_rules.xml",
        "data/sequence.xml",
        "views/school_master_data_views.xml",
        "views/res_partner_views.xml",
        "views/fee_batch_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/account_journal_views.xml",
        "views/budget_asset_views.xml",
        "views/dashboard_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/account_move_reversal_views.xml",
        "wizard/account_payment_register_views.xml",
        "wizard/demo_generator_views.xml",
        "report/account_document_templates.xml",
        "views/school_finance_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "school_finance/static/src/accounting_overview/accounting_overview.js",
            "school_finance/static/src/accounting_overview/accounting_overview.xml",
            "school_finance/static/src/accounting_overview/accounting_overview.scss",
        ],
    },
    "application": False,
    "installable": True,
}
